on:
  issues:
    types:
      - labeled

jobs:
  add-symbols:
    if: github.event.label.name == 'approved'
    permissions:
      contents: write
      issues: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/mcapi-request.yml

      - run: |
          echo $ISSUE_PARSER_RESULT >> issue-parser-result.json
          python update_symbols.py
        env:
          ISSUE_PARSER_RESULT: ${{ steps.issue-parser.outputs.jsonString }}

      - uses: stefanzweifel/git-auto-commit-action@v5
