on:
  issues:
    types:
      - labeled

jobs:
  add-symbols:
    if: github.event.label.name == 'approved'
    permissions:
      contents: write
      issues: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "${{ github.event.issue.body }}"
